{% set name = "jonga" %}
{% set version = "0.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jonga-{{ version }}.tar.gz
  sha256: d258421c66887cb10122d3237e06bc5b14a4809fdcef4654b62dc2e397fb0892

build:
  number: 1005
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - pytest-runner
  run:
    - python >={{ python_min }}
    - pygraphviz

test:
  imports:
    - jonga
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bwohlberg/jonga
  license: GPL-2.0-or-later
  license_family: GPL2
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Python function call graph visualization'
  description: |
    Jonga is a Python package that generates a directed graph representing
    function calls within a block of Python code, intended for inclusion
    in Sphinx package documentation.
  doc_url: https://jonga.readthedocs.io/en/latest
  dev_url: https://github.com/bwohlberg/jonga

extra:
  recipe-maintainers:
    - bwohlberg
