{% set name = "jonga" %}
{% set version = "0.0.4" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  'sha256': 'd258421c66887cb10122d3237e06bc5b14a4809fdcef4654b62dc2e397fb0892'

build:
  number: 1002
  skip: True  # [win or py2k]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
    - pygraphviz
    - pytest
    - pytest-runner
  run:
    - python
    - pygraphviz

test:
  imports:
    - jonga

about:
  home: https://github.com/bwohlberg/jonga
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Python function call graph visualization'
  description: |
    Jonga is a Python package that generates a directed graph representing
    function calls within a block of Python code, intended for inclusion
    in Sphinx package documentation.
  doc_url: https://jonga.readthedocs.io/en/latest
  dev_url: https://github.com/bwohlberg/jonga

extra:
  recipe-maintainers:
    - bwohlberg
