travis:
  secure:
    BINSTAR_TOKEN: iKbTg3CsAmh17V/JL5npOYlubnfrk261Vk0/S510wgYTVFACRMaUmteWkEuNMyhKfAFwRI1yEpxu6eFe8532Gxn0jGruWZF4MK39148hLCcdjp9NMufDcatt52UHsBafTprX2SScSnW7dXp+0kzYi+eyMF+a5Xa+IPmHGmZ3rsvJEnUZI9Fj1PMbIKnCMQ8LinWEIehJCkFEfhcG+FP6gaFFKckbnDw43WGLmsEL/+E0QedLjO6yi5VGStabKoS51BVgs1y0tUHy6IubOQnj6KmLNvolBAomZW7MAm5zvCFbvaiUafXHQ+HygoBKZlkr+nLnceBogG69FBKT4tPqgtxYDq5EX1ar7OUCple8psx/4LhpkM9pBz+YBj5a7tvzqugygETzffbXIui/46zDY8bT3XUJ35GnZkuBYUVCCKD1tzyC0JRsn5KeZD9nvTT7HfuAXaJTF5IXuU5TcaUbGOVOw2Q8fJvAOHaTruRPX8ZWv7kaa5JI5osbjtSWeTlc17hsEhBUYNLlVX0k7c3QXGWIIR7egfAE8hBmb97dkKCK9rcKEDLmb3D1eaOFXSPoStHRbzR4wtEjIV/iI1SDIpb+P1/w4KEct8kldb8NyhnLwYQD+LaAkUYAHIUlRwfj6F87BS4LQdAGfAZq19keO9u+uL/BbByjEx7a04EkzUQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
